# action.yml
name: 'Scan Action Logs'
description: 'Identify potential leaks in GitHub action logs'
branding:
  icon: 'search'  
  color: 'red'
inputs:
  github-token:
    description: 'Token used to login to GitHub'
    required: true
  repo:
    description: 'Repo to scan run logs for exceptions'
    required: true
  run-limit:
    description: 'Limit on how many runs to scan'
    required: true
    default: '50'
outputs:
  exceptions:
    description: 'json output of run logs with exceptions'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.repo }}
    - ${{ inputs.run-limit }}