name: Scan Action Logs

on: [push]

jobs:
  scan_run_logs:
    runs-on: ubuntu-latest
    name: Scan repo run logs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scan run logs
        uses: ./
        id: scan
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          repo:  ${{ secrets.SCAN_REPO }}
          run-limit: 300
          min-days-old: 7
          max-days-old: 10
          patterns-path: ".runleaks/patterns.txt"
          exclusions-path: ".runleaks/exclusions.txt"
      - name: Get scan exceptions
        run: |
          echo "${{ steps.scan.outputs.exceptions }}"
          echo "${{ steps.scan.outputs.exceptions }}" | jq length
