name: Scan Action Logs

on: [push]

jobs:
  scan_run_logs:
    runs-on: ubuntu-latest
    name: Scan repo run logs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scan run logs
        uses: ./
        id: scan
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get scan exceptions
        run: echo "${{ steps.scan.outputs.exceptions }}"
